CONFIG_CONSOLE_SUBSYS=y

# Must be INF or DBG to enable NV writes and prompting to allow a write.
CONFIG_APP_BATTERY_LOG_LEVEL_DBG=y

# Print MAX17205 NV registers, capacity history, and flash storage details.
CONFIG_VERBOSE_DEBUG=y

# If CONFIG_VERBOSE_DEBUG also y, allow writing to the MAX17205 NV memory; limited to 7 times
# by MAX17205 hardware.
CONFIG_ENABLE_NV_MEMORY_UPDATE_CODE=y

# If CONFIG_VERBOSE_DEBUG also y, allow check for MAX17205 battery characteristic learning
# level detection. If level == 7, it is complete, so write maximum rated capacity to MIXCAP
# and REPCAP registers, which are the ones our custom history storage in hist.c keep track of.
CONFIG_ENABLE_LEARN_COMPLETE=y

# At the very end of any charge/discharge use prior to launch, set this and
# CONFIG_APP_BATTERY_LOG_LEVEL_DBG=y. The next time the battery thread decides to store the
# capacity history (at 5 minutes of uptime), a prompt will appear on the terminal:
#    ********** Store batt_hist e(rase), t(est), y(es), n(o)? 
# Answer with e to clear out old battery history, then shortly thereafter, shutdown the card
# (the battery must be fully charged). The battery card physical shutdown switches should be
# depressed soon so that battery capacity loss is minimized as much as possible until the launch
# vehicle releases the satellite in orbit. This ensures the learned nominal maximum capacity
# of the batteries is assumed to be the actual capacity as the starting point during normal
# operations in orbit.
CONFIG_HIST_STORE_PROMPT=n
