CONFIG_GPIO=y
CONFIG_SENSOR=y
CONFIG_CAN=y
CONFIG_CAN_DEFAULT_BITRATE=1000000
CONFIG_CANOPENNODE_V4=y
CONFIG_REBOOT=y
CONFIG_MAX17205=y

CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y

CONFIG_FCB=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SOC_FLASH_STM32=y

CONFIG_ORESAT_COMMON_LIB=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_RUNTIME_FILTERING=n
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=0
CONFIG_LOG_TAG_MAX_LEN=8

CONFIG_I2C_LOG_LEVEL_INF=y
CONFIG_APP_BATTERY_LOG_LEVEL_DBG=y
CONFIG_SENSOR_LOG_LEVEL_INF=y
CONFIG_CANOPENNODE_V4_LOG_LEVEL_DBG=y

CONFIG_APPLICATION_INIT_PRIORITY=91
CONFIG_COVERAGE=n

CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_DEBUG_OPTIMIZATIONS=y
#CONFIG_HW_STACK_PROTECTION=y
CONFIG_INIT_STACKS=y
CONFIG_STACK_SENTINEL=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=1024

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=10
