// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
// For CANopenNode V2 users, C macro `CO_VERSION_MAJOR=2` has to be added to project options
#ifndef CO_VERSION_MAJOR
 #include "CO_driver.h"
 #include "CO_OD.h"
 #include "CO_SDO.h"
#elif CO_VERSION_MAJOR < 4
 #include "301/CO_driver.h"
 #include "CO_OD.h"
 #include "301/CO_SDOserver.h"
#else
 #error This Object dictionary is not compatible with CANopenNode v4.0 and up!
#endif

/*******************************************************************************
   DEFINITION AND INITIALIZATION OF OBJECT DICTIONARY VARIABLES
*******************************************************************************/


/***** Definition for RAM variables *******************************************/
struct sCO_OD_RAM CO_OD_RAM = {
           CO_OD_FIRST_LAST_WORD,

/*1000*/ 0x0000L,
/*1001*/ 0x0L,
/*1003*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1005*/ 0x0080L,
/*1006*/ 0x0000L,
/*1007*/ 0x0000L,
/*1014*/ 0x0084L,
/*1015*/ 0x00,
/*1016*/ {0x0000L},
/*1017*/ 0x3E8,
/*1018*/ {0x4L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1019*/ 0x0L,
/*1029*/ {0x0L},
/*1200*/ {{0x3L, 0x80000000L, 0x80000000L, 0x1L}},
/*1400*/ {{0x5L, 0x0180L, 0xFEL, 0x00}},
/*1600*/ {{0x1L, 0x20100040L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L}},
/*1800*/ {{0x6L, 0x0184L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1801*/ {0x6L, 0x0284L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1802*/ {0x6L, 0x0384L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1803*/ {0x6L, 0x0484L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1804*/ {0x6L, 0x0185L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1805*/ {0x6L, 0x0285L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1806*/ {0x6L, 0x0385L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1807*/ {0x6L, 0x0485L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1808*/ {0x6L, 0x0186L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L},
/*1809*/ {0x6L, 0x0286L, 0xFEL, 0x00, 0x0L, 0x7D0, 0x0L}},
/*1A00*/ {{0x4L, 0x40000110L, 0x40000210L, 0x40000310L, 0x40000410L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A01*/ {0x3L, 0x40000510L, 0x40000610L, 0x40000710L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A02*/ {0x4L, 0x40000810L, 0x40000910L, 0x40000A10L, 0x40000B10L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A03*/ {0x4L, 0x40001208L, 0x40001308L, 0x40001408L, 0x40001508L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A04*/ {0x4L, 0x40000C10L, 0x40000D10L, 0x40001108L, 0x40001608L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A05*/ {0x4L, 0x40010110L, 0x40010210L, 0x40010310L, 0x40010410L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A06*/ {0x3L, 0x40010510L, 0x40010610L, 0x40010710L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A07*/ {0x4L, 0x40010810L, 0x40010910L, 0x40010A10L, 0x40010B10L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A08*/ {0x4L, 0x40011208L, 0x40011308L, 0x40011408L, 0x40011508L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A09*/ {0x4L, 0x40010C10L, 0x40010D10L, 0x40011108L, 0x40011608L, 0x0000L, 0x0000L, 0x0000L, 0x0000L}},
/*1F50*/ {0},
/*1F51*/ {0x0L},
/*1F56*/ {0x0000L},
/*1F57*/ {0x0000L},
/*1F80*/ 0x0000L,
/*2010*/ 0x00000000L,
/*2011*/ 0x00000000L,
/*2100*/ {0x0L},
/*3000*/ 0x3L,
/*3001*/ 0x01,
/*3002*/ {0x4L, {'0', '.', '0'}, {'1', '.', '2', '.', '0'}, {'0', '.', '0', '.', '0'}},
/*3003*/ {0x8L, 0x0L, 0x0000L, 0x0, 0x00},
/*3009*/ 0x0L,
/*4000*/ {0x16L, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0L, 0x0, 0x0, 0x0, 0x0, 0x0L},
/*4001*/ {0x16L, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0L, 0x0, 0x0, 0x0, 0x0, 0x0L},

           CO_OD_FIRST_LAST_WORD,
};


/***** Definition for ROM variables *******************************************/
struct sCO_OD_ROM CO_OD_ROM = {
           CO_OD_FIRST_LAST_WORD,


           CO_OD_FIRST_LAST_WORD,
};


/***** Definition for EEPROM variables *******************************************/
struct sCO_OD_EEPROM CO_OD_EEPROM = {
           CO_OD_FIRST_LAST_WORD,


           CO_OD_FIRST_LAST_WORD,
};




/*******************************************************************************
   STRUCTURES FOR RECORD TYPE OBJECTS
*******************************************************************************/


/*0x1018*/ const CO_OD_entryRecord_t OD_record1018[5] = {
           {(void*)&CO_OD_RAM.identity.highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.identity.vendorID, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.identity.productCode, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.identity.revisionNumber, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.identity.serialNumber, 0xB6, 0x4 },
};

/*0x1200*/ const CO_OD_entryRecord_t OD_record1200[4] = {
           {(void*)&CO_OD_RAM.SDOServerParameter[0].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.SDOServerParameter[0].COB_IDClientToServer, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.SDOServerParameter[0].COB_IDServerToClient, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.SDOServerParameter[0].node_id_od_sdo_client, 0x36, 0x1 },
};

/*0x1400*/ const CO_OD_entryRecord_t OD_record1400[4] = {
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].event_timer, 0x86, 0x2 },
};

/*0x1600*/ const CO_OD_entryRecord_t OD_record1600[9] = {
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_2, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_3, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_4, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].mapping_object_8, 0x8E, 0x4 },
};

/*0x1800*/ const CO_OD_entryRecord_t OD_record1800[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].sync_start_value, 0x06, 0x1 },
};

/*0x1801*/ const CO_OD_entryRecord_t OD_record1801[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].sync_start_value, 0x06, 0x1 },
};

/*0x1802*/ const CO_OD_entryRecord_t OD_record1802[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].sync_start_value, 0x06, 0x1 },
};

/*0x1803*/ const CO_OD_entryRecord_t OD_record1803[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].sync_start_value, 0x06, 0x1 },
};

/*0x1804*/ const CO_OD_entryRecord_t OD_record1804[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[4].sync_start_value, 0x06, 0x1 },
};

/*0x1805*/ const CO_OD_entryRecord_t OD_record1805[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[5].sync_start_value, 0x06, 0x1 },
};

/*0x1806*/ const CO_OD_entryRecord_t OD_record1806[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[6].sync_start_value, 0x06, 0x1 },
};

/*0x1807*/ const CO_OD_entryRecord_t OD_record1807[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[7].sync_start_value, 0x06, 0x1 },
};

/*0x1808*/ const CO_OD_entryRecord_t OD_record1808[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[8].sync_start_value, 0x06, 0x1 },
};

/*0x1809*/ const CO_OD_entryRecord_t OD_record1809[7] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].cob_id, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].transmission_type, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].inhibit_time, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].event_timer, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[9].sync_start_value, 0x06, 0x1 },
};

/*0x1A00*/ const CO_OD_entryRecord_t OD_record1A00[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A01*/ const CO_OD_entryRecord_t OD_record1A01[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_4, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A02*/ const CO_OD_entryRecord_t OD_record1A02[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A03*/ const CO_OD_entryRecord_t OD_record1A03[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A04*/ const CO_OD_entryRecord_t OD_record1A04[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[4].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A05*/ const CO_OD_entryRecord_t OD_record1A05[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[5].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A06*/ const CO_OD_entryRecord_t OD_record1A06[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_4, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[6].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A07*/ const CO_OD_entryRecord_t OD_record1A07[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[7].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A08*/ const CO_OD_entryRecord_t OD_record1A08[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[8].mapping_object_8, 0x8E, 0x4 },
};

/*0x1A09*/ const CO_OD_entryRecord_t OD_record1A09[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_4, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[9].mapping_object_8, 0x8E, 0x4 },
};

/*0x3002*/ const CO_OD_entryRecord_t OD_record3002[4] = {
           {(void*)&CO_OD_RAM.versions.highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.versions.hw_version, 0x06, 0x3 },
           {(void*)&CO_OD_RAM.versions.configs_version, 0x06, 0x5 },
           {(void*)&CO_OD_RAM.versions.fw_version, 0x06, 0x5 },
};

/*0x3003*/ const CO_OD_entryRecord_t OD_record3003[5] = {
           {(void*)&CO_OD_RAM.system.highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.system.reset, 0x3A, 0x1 },
           {(void*)&CO_OD_RAM.system.uptime, 0xB6, 0x4 },
           {(void*)&CO_OD_RAM.system.temperature, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.system.vrefint, 0xB6, 0x2 },
};

/*0x4000*/ const CO_OD_entryRecord_t OD_record4000[23] = {
           {(void*)&CO_OD_RAM.pack_1.highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.vbatt, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell_max, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell_min, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell_1, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell_2, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.vcell_avg, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.current, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.current_avg, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.current_max, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.current_min, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.full_capacity, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.reported_capacity, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.time_to_empty, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.time_to_full, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.cycles, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_1.reported_state_of_charge, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.temperature, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.temperature_avg, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.temperature_max, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.temperature_min, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_1.status, 0x36, 0x1 },
};

/*0x4001*/ const CO_OD_entryRecord_t OD_record4001[23] = {
           {(void*)&CO_OD_RAM.pack_2.highest_index_supported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.vbatt, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell_max, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell_min, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell_1, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell_2, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.vcell_avg, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.current, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.current_avg, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.current_max, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.current_min, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.full_capacity, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.reported_capacity, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.time_to_empty, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.time_to_full, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.cycles, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.pack_2.reported_state_of_charge, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.temperature, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.temperature_avg, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.temperature_max, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.temperature_min, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.pack_2.status, 0x36, 0x1 },
};

/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
const CO_OD_entry_t CO_OD[CO_OD_NoOfElements] = {
{0x1000, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.device_type},
{0x1001, 0x00, 0x36,  1, (void*)&CO_OD_RAM.errorRegister},
{0x1003, 0x08, 0x8A,  4, (void*)&CO_OD_RAM.preDefinedErrorField[0]},
{0x1005, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.COB_ID_SYNCMessage},
{0x1006, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.communicationCyclePeriod},
{0x1007, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.synchronousWindowLength},
{0x1014, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.cob_id_emergency_message},
{0x1015, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.inhibitTimeEMCY},
{0x1016, 0x01, 0x82,  4, (void*)&CO_OD_RAM.consumerHeartbeatTime[0]},
{0x1017, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.producerHeartbeatTime},
{0x1018, 0x04, 0x00,  0, (void*)&OD_record1018},
{0x1019, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.synchronousCounterOverflowValue},
{0x1029, 0x01, 0x82,  4, (void*)&CO_OD_RAM.errorBehavior[0]},
{0x1200, 0x03, 0x00,  0, (void*)&OD_record1200},
{0x1400, 0x03, 0x00,  0, (void*)&OD_record1400},
{0x1600, 0x08, 0x00,  0, (void*)&OD_record1600},
{0x1800, 0x06, 0x00,  0, (void*)&OD_record1800},
{0x1801, 0x06, 0x00,  0, (void*)&OD_record1801},
{0x1802, 0x06, 0x00,  0, (void*)&OD_record1802},
{0x1803, 0x06, 0x00,  0, (void*)&OD_record1803},
{0x1804, 0x06, 0x00,  0, (void*)&OD_record1804},
{0x1805, 0x06, 0x00,  0, (void*)&OD_record1805},
{0x1806, 0x06, 0x00,  0, (void*)&OD_record1806},
{0x1807, 0x06, 0x00,  0, (void*)&OD_record1807},
{0x1808, 0x06, 0x00,  0, (void*)&OD_record1808},
{0x1809, 0x06, 0x00,  0, (void*)&OD_record1809},
{0x1A00, 0x08, 0x00,  0, (void*)&OD_record1A00},
{0x1A01, 0x08, 0x00,  0, (void*)&OD_record1A01},
{0x1A02, 0x08, 0x00,  0, (void*)&OD_record1A02},
{0x1A03, 0x08, 0x00,  0, (void*)&OD_record1A03},
{0x1A04, 0x08, 0x00,  0, (void*)&OD_record1A04},
{0x1A05, 0x08, 0x00,  0, (void*)&OD_record1A05},
{0x1A06, 0x08, 0x00,  0, (void*)&OD_record1A06},
{0x1A07, 0x08, 0x00,  0, (void*)&OD_record1A07},
{0x1A08, 0x08, 0x00,  0, (void*)&OD_record1A08},
{0x1A09, 0x08, 0x00,  0, (void*)&OD_record1A09},
{0x1F50, 0x01, 0x82,  4, (void*)&CO_OD_RAM.program_data[0]},
{0x1F51, 0x01, 0x82,  4, (void*)&CO_OD_RAM.program_control[0]},
{0x1F56, 0x01, 0x82,  4, (void*)&CO_OD_RAM.program_software_identification[0]},
{0x1F57, 0x01, 0x82,  4, (void*)&CO_OD_RAM.flash_status_identification[0]},
{0x1F80, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.NMTStartup},
{0x2010, 0x00, 0xBE,  8, (void*)&CO_OD_RAM.scet},
{0x2011, 0x00, 0xBE,  8, (void*)&CO_OD_RAM.utc},
{0x2100, 0x00, 0x0E, 10, (void*)&CO_OD_RAM.errorStatusBits},
{0x3000, 0x00, 0x36,  1, (void*)&CO_OD_RAM.satellite_id},
{0x3001, 0x00, 0x36,  1, (void*)&CO_OD_RAM.flight_mode},
{0x3002, 0x03, 0x00,  0, (void*)&OD_record3002},
{0x3003, 0x04, 0x00,  0, (void*)&OD_record3003},
{0x3009, 0x00, 0x36,  1, (void*)&CO_OD_RAM.board_id},
{0x4000, 0x16, 0x00,  0, (void*)&OD_record4000},
{0x4001, 0x16, 0x00,  0, (void*)&OD_record4001},
};
// clang-format on
